create database if not exists pizza;
use pizza;
create table pizzamenu (pizzaname VARCHAR(100) not null, topping VARCHAR(50) not null, size VARCHAR(20) not null, pizzaid int not null Primary Key, price int not null);
Insert into pizzamenu values ('Margherita', 'extra cheese', 'L',101 , 400), ('Farmhouse', 'extra cheese', 'M', 102, 300), ('Barbecue veg', 'veg topping', 'S', 104, 450), ('Tandoori veg', 'veg topping', 'M', 105, 290);
create table crust(crust_name VARCHAR(50), crustid int, rate int);
insert into crust values ('hand tossed', 12, 60), ('wheat thin', 13, 70), ('fresh pan base', 15, 50);
select * from pizzamenu;
drop table crust;
create table customers (cust_name varchar(20) not null, customerid int not null primary key, phoneno varchar(50) not null, address varchar(100) not null);
insert into customers values ('Neha', 1001, '9877467333', 'Lodhi Road, Delhi'), ('Prerna', 1006, '9877465633', 'Maharani Bagh, Delhi'), ('Aayushi', 1008, '7977467333', 'Preet Vihar, Delhi'), ('Kartik', 1003, '9877409333', 'Lajpat Nagar, Delhi');
select * from customers;
create table orders (orderid int primary key not null, customerid int, orderdate date not null, amount int, servetype varchar(50), pizzaid int, constraint customerid foreign key (pizzaid) references pizzamenu(pizzaid));
insert into orders values (1, 1001, '2021-05-23', 560, 'Dinein', 101), (5, 1006, '2021-06-02', 500, 'Delivery', 101), (7, 1003, '2021-05-20', 400, 'Delivery', 104), (2, 1008, '2021-05-01', 700, 'Delivery', 102);
select * from orders;
insert into pizzamenu values ('Non veg', 'extra cheese', 'M', 107, 600);
insert into crust values ('cheeseburst', 20, 100);
select * from pizzamenu;
select customers.cust_name from customers join orders using (customerid) join pizzamenu using (pizzaid) where pizzamenu.size= 'L';
select pizzamenu.topping, count(pizzamenu.topping) from pizzamenu join orders using (pizzaid) group by pizzamenu.topping;
select customers.cust_name, orders.amount from orders join customers using (customerid) order by orders.amount desc limit 1;
select orders.servetype, count(orders.servetype) from orders where orders.servetype = 'Delivery';
update orders join pizzamenu using (pizzaid) set orders.amount = orders.amount - 0.1*orders.amount where pizzamenu.size = 'L';